export const guardianAbi = [
  {type: 'constructor', inputs: [], stateMutability: 'nonpayable'},
  {
    type: 'function',
    name: 'DEFAULT_ADMIN_ROLE',
    inputs: [],
    outputs: [{name: '', type: 'bytes32', internalType: 'bytes32'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIN_WITHDRAW_INTERVAL',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PAUSER_ROLE',
    inputs: [],
    outputs: [{name: '', type: 'bytes32', internalType: 'bytes32'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allowBurn',
    inputs: [{name: 'vault', type: 'address', internalType: 'address'}],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allowEmergencyMarketWithdraw',
    inputs: [{name: 'market', type: 'address', internalType: 'address'}],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allowEmergencyVaultWithdraw',
    inputs: [{name: 'vault', type: 'address', internalType: 'address'}],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allowMint',
    inputs: [{name: 'vault', type: 'address', internalType: 'address'}],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allowTrade',
    inputs: [
      {name: 'market', type: 'address', internalType: 'address'},
      {name: 'owner', type: 'address', internalType: 'address'},
      {name: 'sender', type: 'address', internalType: 'address'},
    ],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRoleAdmin',
    inputs: [{name: 'role', type: 'bytes32', internalType: 'bytes32'}],
    outputs: [{name: '', type: 'bytes32', internalType: 'bytes32'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'globalBurnPaused',
    inputs: [],
    outputs: [
      {name: 'paused', type: 'bool', internalType: 'bool'},
      {name: 'updatedAt', type: 'uint64', internalType: 'uint64'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'globalMintPaused',
    inputs: [],
    outputs: [
      {name: 'paused', type: 'bool', internalType: 'bool'},
      {name: 'updatedAt', type: 'uint64', internalType: 'uint64'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'globalTradingPaused',
    inputs: [],
    outputs: [
      {name: 'paused', type: 'bool', internalType: 'bool'},
      {name: 'updatedAt', type: 'uint64', internalType: 'uint64'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'grantRole',
    inputs: [
      {name: 'role', type: 'bytes32', internalType: 'bytes32'},
      {name: 'account', type: 'address', internalType: 'address'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'hasRole',
    inputs: [
      {name: 'role', type: 'bytes32', internalType: 'bytes32'},
      {name: 'account', type: 'address', internalType: 'address'},
    ],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'marketTradingPaused',
    inputs: [{name: '', type: 'address', internalType: 'address'}],
    outputs: [
      {name: 'paused', type: 'bool', internalType: 'bool'},
      {name: 'updatedAt', type: 'uint64', internalType: 'uint64'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'operatorsPaused',
    inputs: [{name: '', type: 'address', internalType: 'address'}],
    outputs: [
      {name: 'paused', type: 'bool', internalType: 'bool'},
      {name: 'updatedAt', type: 'uint64', internalType: 'uint64'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pauseGlobal',
    inputs: [
      {name: 'mintPaused', type: 'bool', internalType: 'bool'},
      {name: 'burnPaused', type: 'bool', internalType: 'bool'},
      {name: 'TradingPaused', type: 'bool', internalType: 'bool'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pauseMarket',
    inputs: [
      {name: 'market', type: 'address', internalType: 'address'},
      {name: 'TradingPaused', type: 'bool', internalType: 'bool'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pauseOperator',
    inputs: [
      {name: 'operator', type: 'address', internalType: 'address'},
      {name: 'paused', type: 'bool', internalType: 'bool'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'pauseVault',
    inputs: [
      {name: 'vault', type: 'address', internalType: 'address'},
      {name: 'mintPaused', type: 'bool', internalType: 'bool'},
      {name: 'burnPaused', type: 'bool', internalType: 'bool'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceRole',
    inputs: [
      {name: 'role', type: 'bytes32', internalType: 'bytes32'},
      {
        name: 'callerConfirmation',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revokeRole',
    inputs: [
      {name: 'role', type: 'bytes32', internalType: 'bytes32'},
      {name: 'account', type: 'address', internalType: 'address'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{name: 'interfaceId', type: 'bytes4', internalType: 'bytes4'}],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vaultBurnPaused',
    inputs: [{name: '', type: 'address', internalType: 'address'}],
    outputs: [
      {name: 'paused', type: 'bool', internalType: 'bool'},
      {name: 'updatedAt', type: 'uint64', internalType: 'uint64'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vaultMintPaused',
    inputs: [{name: '', type: 'address', internalType: 'address'}],
    outputs: [
      {name: 'paused', type: 'bool', internalType: 'bool'},
      {name: 'updatedAt', type: 'uint64', internalType: 'uint64'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'PauseGlobal',
    inputs: [
      {
        name: 'mintPaused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'burnPaused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'TradingPaused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PauseMarket',
    inputs: [
      {
        name: 'market',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'paused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PauseOperator',
    inputs: [
      {
        name: 'operator',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'paused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PauseVault',
    inputs: [
      {
        name: 'vault',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'mintPaused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'burnPaused',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RoleAdminChanged',
    inputs: [
      {
        name: 'role',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'previousAdminRole',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'newAdminRole',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RoleGranted',
    inputs: [
      {
        name: 'role',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'account',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'sender',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RoleRevoked',
    inputs: [
      {
        name: 'role',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'account',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'sender',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {type: 'error', name: 'AccessControlBadConfirmation', inputs: []},
  {
    type: 'error',
    name: 'AccessControlUnauthorizedAccount',
    inputs: [
      {name: 'account', type: 'address', internalType: 'address'},
      {name: 'neededRole', type: 'bytes32', internalType: 'bytes32'},
    ],
  },
] as const;
