export const optionsMarketAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_vault',
        type: 'address',
        internalType: 'contract ITimelockVault',
      },
      {
        name: '_optionPricing',
        type: 'address',
        internalType: 'contract IOptionPricing',
      },
      {name: '_optionAssetIsToken0', type: 'bool', internalType: 'bool'},
      {
        name: '_swapRouter',
        type: 'address',
        internalType: 'contract ISwapRouter',
      },
      {name: '_quoter', type: 'address', internalType: 'contract IQuoter'},
      {name: '_owner', type: 'address', internalType: 'address'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'BASIS_POINTS',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DUST_THRESHOLD',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_STEPS',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'OPTION_FEE_PERCENT',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'calculatePremium',
    inputs: [
      {name: 'optionType', type: 'uint8', internalType: 'uint8'},
      {name: 'optionAmount', type: 'uint256', internalType: 'uint256'},
      {name: 'strikeTick', type: 'int24', internalType: 'int24'},
      {name: 'duration', type: 'uint64', internalType: 'uint64'},
    ],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'exerciseOption',
    inputs: [
      {name: 'optionId', type: 'uint256', internalType: 'uint256'},
      {name: 'liquidities', type: 'uint128[]', internalType: 'uint128[]'},
      {name: 'minPayout', type: 'uint256', internalType: 'uint256'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [{name: 'payout', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getOption',
    inputs: [{name: 'optionId', type: 'uint256', internalType: 'uint256'}],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct TimelockOptionsMarket.OptionData',
        components: [
          {name: 'owner', type: 'address', internalType: 'address'},
          {name: 'optionType', type: 'uint8', internalType: 'uint8'},
          {name: 'strikeTick', type: 'int24', internalType: 'int24'},
          {name: 'entryTick', type: 'int24', internalType: 'int24'},
          {name: 'expiresAt', type: 'uint64', internalType: 'uint64'},
          {name: 'createdAt', type: 'uint64', internalType: 'uint64'},
          {name: 'premiumPaid', type: 'uint128', internalType: 'uint128'},
          {name: 'liquidities', type: 'uint128[]', internalType: 'uint128[]'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'liquiditiesToAmounts',
    inputs: [
      {name: 'leftTick', type: 'int24', internalType: 'int24'},
      {name: 'liquidities', type: 'uint128[]', internalType: 'uint128[]'},
      {name: 'optionType', type: 'uint8', internalType: 'uint8'},
    ],
    outputs: [
      {name: 'optionAssetToRepay', type: 'uint256', internalType: 'uint256'},
      {name: 'payoutAssetToRepay', type: 'uint256', internalType: 'uint256'},
      {name: 'optionAssetBorrowed', type: 'uint256', internalType: 'uint256'},
      {name: 'payoutAssetBorrowed', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxDuration',
    inputs: [],
    outputs: [{name: '', type: 'uint64', internalType: 'uint64'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxOptionAmount',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minDuration',
    inputs: [],
    outputs: [{name: '', type: 'uint64', internalType: 'uint64'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minOptionAmount',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mintOption',
    inputs: [
      {name: 'optionType', type: 'uint8', internalType: 'uint8'},
      {name: 'amount', type: 'uint256', internalType: 'uint256'},
      {name: 'strikeTick', type: 'int24', internalType: 'int24'},
      {name: 'duration', type: 'uint64', internalType: 'uint64'},
      {name: 'maxPremium', type: 'uint256', internalType: 'uint256'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'optionId', type: 'uint256', internalType: 'uint256'},
      {name: 'finalAmount', type: 'uint256', internalType: 'uint256'},
      {name: 'totalPremium', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'nextOptionId',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'optionAsset',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'contract IERC20'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'optionAssetIsToken0',
    inputs: [],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'optionPricing',
    inputs: [],
    outputs: [
      {name: '', type: 'address', internalType: 'contract IOptionPricing'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'address'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'payoutAsset',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'contract IERC20'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pool',
    inputs: [],
    outputs: [
      {name: '', type: 'address', internalType: 'contract IUniswapV3Pool'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'protocolFees',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'quoter',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'contract IQuoter'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'swapRouter',
    inputs: [],
    outputs: [
      {name: '', type: 'address', internalType: 'contract ISwapRouter'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tickSpacing',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'token0',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'contract IERC20'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'token1',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'contract IERC20'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{name: 'newOwner', type: 'address', internalType: 'address'}],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateDurationBounds',
    inputs: [
      {name: '_minDuration', type: 'uint64', internalType: 'uint64'},
      {name: '_maxDuration', type: 'uint64', internalType: 'uint64'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateOptionAmountBounds',
    inputs: [
      {name: '_minOptionAmount', type: 'uint256', internalType: 'uint256'},
      {name: '_maxOptionAmount', type: 'uint256', internalType: 'uint256'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'vault',
    inputs: [],
    outputs: [
      {name: '', type: 'address', internalType: 'contract ITimelockVault'},
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'withdrawTokens',
    inputs: [
      {name: 'tokens', type: 'address[]', internalType: 'contract IERC20[]'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const;
