export const singleOwnerVaultAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_pool',
        type: 'address',
        internalType: 'contract IUniswapV3Pool',
      },
      {name: '_owner', type: 'address', internalType: 'address'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'BORROW',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'BURN',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MINT',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIN_DUST_THRESHOLD',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'REPAY',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'blocks',
    inputs: [{name: '', type: 'int24', internalType: 'int24'}],
    outputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'prevTickLower', type: 'int24', internalType: 'int24'},
      {
        name: 'totalLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
      {
        name: 'borrowedLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'blocksCount',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'borrow',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'amount0', type: 'uint256', internalType: 'uint256'},
      {name: 'amount1', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'borrowerWhitelist',
    inputs: [{name: '', type: 'address', internalType: 'address'}],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'burn',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'amount0', type: 'uint256', internalType: 'uint256'},
      {name: 'amount1', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'collectFees',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {
        name: 'totalAmount0',
        type: 'uint256',
        internalType: 'uint256',
      },
      {name: 'totalAmount1', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getBlock',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct TimelockVaultCore.LiquidityBlock',
        components: [
          {name: 'tickLower', type: 'int24', internalType: 'int24'},
          {name: 'tickUpper', type: 'int24', internalType: 'int24'},
          {
            name: 'prevTickLower',
            type: 'int24',
            internalType: 'int24',
          },
          {
            name: 'totalLiquidity',
            type: 'uint128',
            internalType: 'uint128',
          },
          {
            name: 'borrowedLiquidity',
            type: 'uint128',
            internalType: 'uint128',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'highestTick',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lowestTick',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'amount0', type: 'uint256', internalType: 'uint256'},
      {name: 'amount1', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{name: 'data', type: 'bytes[]', internalType: 'bytes[]'}],
    outputs: [{name: 'results', type: 'bytes[]', internalType: 'bytes[]'}],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'address'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pool',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IUniswapV3Pool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pool_',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IUniswapV3Pool',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'repay',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'amount0', type: 'uint256', internalType: 'uint256'},
      {name: 'amount1', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'tickSpacing',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'token0',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'contract IERC20'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'token1',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'contract IERC20'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{name: 'newOwner', type: 'address', internalType: 'address'}],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'uniswapV3MintCallback',
    inputs: [
      {name: 'amount0', type: 'uint256', internalType: 'uint256'},
      {name: 'amount1', type: 'uint256', internalType: 'uint256'},
      {name: 'data', type: 'bytes', internalType: 'bytes'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'whitelistBorrower',
    inputs: [
      {name: 'borrower', type: 'address', internalType: 'address'},
      {name: 'status', type: 'bool', internalType: 'bool'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawTokens',
    inputs: [
      {
        name: 'tokens',
        type: 'address[]',
        internalType: 'contract IERC20[]',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const;
