export const singleOwnerVaultAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_poolManager',
        type: 'address',
        internalType: 'contract IPoolManager',
      },
      {
        name: '_poolKey',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          {
            name: 'currency0',
            type: 'address',
            internalType: 'Currency',
          },
          {
            name: 'currency1',
            type: 'address',
            internalType: 'Currency',
          },
          {name: 'fee', type: 'uint24', internalType: 'uint24'},
          {name: 'tickSpacing', type: 'int24', internalType: 'int24'},
          {
            name: 'hooks',
            type: 'address',
            internalType: 'contract IHooks',
          },
        ],
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'BORROW',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'BURN',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MINT',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'REPAY',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'blocks',
    inputs: [{name: '', type: 'int24', internalType: 'int24'}],
    outputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'prevTickLower', type: 'int24', internalType: 'int24'},
      {
        name: 'totalLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
      {
        name: 'borrowedLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'blocksCount',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'borrow',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'delta0', type: 'int256', internalType: 'int256'},
      {name: 'delta1', type: 'int256', internalType: 'int256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'borrowerWhitelist',
    inputs: [{name: '', type: 'address', internalType: 'address'}],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'burn',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'amount0', type: 'int256', internalType: 'int256'},
      {name: 'amount1', type: 'int256', internalType: 'int256'},
      {name: 'fees0', type: 'uint256', internalType: 'uint256'},
      {name: 'fees1', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getBlock',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct TimelockVaultCore.LiquidityBlock',
        components: [
          {name: 'tickLower', type: 'int24', internalType: 'int24'},
          {name: 'tickUpper', type: 'int24', internalType: 'int24'},
          {
            name: 'prevTickLower',
            type: 'int24',
            internalType: 'int24',
          },
          {
            name: 'totalLiquidity',
            type: 'uint128',
            internalType: 'uint128',
          },
          {
            name: 'borrowedLiquidity',
            type: 'uint128',
            internalType: 'uint128',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'highestTick',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lowestTick',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'amount0', type: 'int256', internalType: 'int256'},
      {name: 'amount1', type: 'int256', internalType: 'int256'},
      {name: 'fees0', type: 'uint256', internalType: 'uint256'},
      {name: 'fees1', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{name: 'data', type: 'bytes[]', internalType: 'bytes[]'}],
    outputs: [{name: 'results', type: 'bytes[]', internalType: 'bytes[]'}],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'address'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolKey',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          {
            name: 'currency0',
            type: 'address',
            internalType: 'Currency',
          },
          {
            name: 'currency1',
            type: 'address',
            internalType: 'Currency',
          },
          {name: 'fee', type: 'uint24', internalType: 'uint24'},
          {name: 'tickSpacing', type: 'int24', internalType: 'int24'},
          {
            name: 'hooks',
            type: 'address',
            internalType: 'contract IHooks',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolManager',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPoolManager',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'repay',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'delta0', type: 'int256', internalType: 'int256'},
      {name: 'delta1', type: 'int256', internalType: 'int256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'settleAndTake',
    inputs: [],
    outputs: [
      {name: 'delta0', type: 'int256', internalType: 'int256'},
      {name: 'delta1', type: 'int256', internalType: 'int256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{name: 'newOwner', type: 'address', internalType: 'address'}],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'unlockCallback',
    inputs: [{name: 'rawData', type: 'bytes', internalType: 'bytes'}],
    outputs: [{name: '', type: 'bytes', internalType: 'bytes'}],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'whitelistBorrower',
    inputs: [
      {name: 'borrower', type: 'address', internalType: 'address'},
      {name: 'status', type: 'bool', internalType: 'bool'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawTokens',
    inputs: [
      {
        name: 'tokens',
        type: 'address[]',
        internalType: 'contract IERC20[]',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Borrow',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'tickLower',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'tickUpper',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'liquidity',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BorrowerWhitelisted',
    inputs: [
      {
        name: 'borrower',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'status',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Burn',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'tickLower',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'tickUpper',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'liquidity',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Mint',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'tickLower',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'tickUpper',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'liquidity',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Repay',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'tickLower',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'tickUpper',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'liquidity',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TokenWithdrawn',
    inputs: [
      {
        name: 'token',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'AddressEmptyCode',
    inputs: [{name: 'target', type: 'address', internalType: 'address'}],
  },
  {
    type: 'error',
    name: 'BorrowerNotWhitelisted',
    inputs: [{name: 'borrower', type: 'address', internalType: 'address'}],
  },
  {type: 'error', name: 'FailedCall', inputs: []},
  {
    type: 'error',
    name: 'InsufficientLiquidity',
    inputs: [
      {name: 'blockTickLower', type: 'int24', internalType: 'int24'},
      {name: 'required', type: 'uint128', internalType: 'uint128'},
    ],
  },
  {
    type: 'error',
    name: 'InvalidActionType',
    inputs: [{name: 'actionType', type: 'uint8', internalType: 'uint8'}],
  },
  {
    type: 'error',
    name: 'InvalidRefTick',
    inputs: [{name: 'tickLower', type: 'int24', internalType: 'int24'}],
  },
  {
    type: 'error',
    name: 'InvalidTickRange',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
    ],
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{name: 'owner', type: 'address', internalType: 'address'}],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{name: 'account', type: 'address', internalType: 'address'}],
  },
  {type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: []},
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{name: 'token', type: 'address', internalType: 'address'}],
  },
  {
    type: 'error',
    name: 'TooMuchRepay',
    inputs: [
      {name: 'blockTickLower', type: 'int24', internalType: 'int24'},
      {name: 'attempted', type: 'uint128', internalType: 'uint128'},
      {name: 'maximum', type: 'uint128', internalType: 'uint128'},
    ],
  },
  {type: 'error', name: 'UnauthorizedCaller', inputs: []},
] as const;
