export const singleOwnerVaultAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: 'poolManager_',
        type: 'address',
        internalType: 'contract IPoolManager',
      },
      {
        name: 'poolKey_',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          {
            name: 'currency0',
            type: 'address',
            internalType: 'Currency',
          },
          {
            name: 'currency1',
            type: 'address',
            internalType: 'Currency',
          },
          {name: 'fee', type: 'uint24', internalType: 'uint24'},
          {name: 'tickSpacing', type: 'int24', internalType: 'int24'},
          {
            name: 'hooks',
            type: 'address',
            internalType: 'contract IHooks',
          },
        ],
      },
      {name: 'owner_', type: 'address', internalType: 'address'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'ADMIN_ROLE',
    inputs: [],
    outputs: [{name: '', type: 'bytes32', internalType: 'bytes32'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'BORROW',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'BORROWER_ROLE',
    inputs: [],
    outputs: [{name: '', type: 'bytes32', internalType: 'bytes32'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'BURN',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DEFAULT_ADMIN_ROLE',
    inputs: [],
    outputs: [{name: '', type: 'bytes32', internalType: 'bytes32'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MINT',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'REPAY',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'RESERVE',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'blocks',
    inputs: [{name: '', type: 'int24', internalType: 'int24'}],
    outputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'prevTickLower', type: 'int24', internalType: 'int24'},
      {
        name: 'totalLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
      {
        name: 'borrowedLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
      {
        name: 'reservedLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'blocksCount',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'borrow',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'delta0', type: 'int256', internalType: 'int256'},
      {name: 'delta1', type: 'int256', internalType: 'int256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'burn',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
      {name: 'amount0Min', type: 'int256', internalType: 'int256'},
      {name: 'amount1Min', type: 'int256', internalType: 'int256'},
      {name: 'deadline', type: 'uint256', internalType: 'uint256'},
    ],
    outputs: [
      {name: 'amount0', type: 'int256', internalType: 'int256'},
      {name: 'amount1', type: 'int256', internalType: 'int256'},
      {name: 'fees0', type: 'uint256', internalType: 'uint256'},
      {name: 'fees1', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getBlock',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct TimelockVaultCore.LiquidityBlock',
        components: [
          {name: 'tickLower', type: 'int24', internalType: 'int24'},
          {name: 'tickUpper', type: 'int24', internalType: 'int24'},
          {
            name: 'prevTickLower',
            type: 'int24',
            internalType: 'int24',
          },
          {
            name: 'totalLiquidity',
            type: 'uint128',
            internalType: 'uint128',
          },
          {
            name: 'borrowedLiquidity',
            type: 'uint128',
            internalType: 'uint128',
          },
          {
            name: 'reservedLiquidity',
            type: 'uint128',
            internalType: 'uint128',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRoleAdmin',
    inputs: [{name: 'role', type: 'bytes32', internalType: 'bytes32'}],
    outputs: [{name: '', type: 'bytes32', internalType: 'bytes32'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'grantRole',
    inputs: [
      {name: 'role', type: 'bytes32', internalType: 'bytes32'},
      {name: 'account', type: 'address', internalType: 'address'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'hasRole',
    inputs: [
      {name: 'role', type: 'bytes32', internalType: 'bytes32'},
      {name: 'account', type: 'address', internalType: 'address'},
    ],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'highestTick',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lowestTick',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
      {name: 'amount0Max', type: 'int256', internalType: 'int256'},
      {name: 'amount1Max', type: 'int256', internalType: 'int256'},
      {name: 'deadline', type: 'uint256', internalType: 'uint256'},
    ],
    outputs: [
      {name: 'amount0', type: 'int256', internalType: 'int256'},
      {name: 'amount1', type: 'int256', internalType: 'int256'},
      {name: 'fees0', type: 'uint256', internalType: 'uint256'},
      {name: 'fees1', type: 'uint256', internalType: 'uint256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{name: 'data', type: 'bytes[]', internalType: 'bytes[]'}],
    outputs: [{name: 'results', type: 'bytes[]', internalType: 'bytes[]'}],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'poolKey',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          {
            name: 'currency0',
            type: 'address',
            internalType: 'Currency',
          },
          {
            name: 'currency1',
            type: 'address',
            internalType: 'Currency',
          },
          {name: 'fee', type: 'uint24', internalType: 'uint24'},
          {name: 'tickSpacing', type: 'int24', internalType: 'int24'},
          {
            name: 'hooks',
            type: 'address',
            internalType: 'contract IHooks',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolManager',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IPoolManager',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renounceRole',
    inputs: [
      {name: 'role', type: 'bytes32', internalType: 'bytes32'},
      {
        name: 'callerConfirmation',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'repay',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {name: 'liquidity', type: 'uint128', internalType: 'uint128'},
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [
      {name: 'delta0', type: 'int256', internalType: 'int256'},
      {name: 'delta1', type: 'int256', internalType: 'int256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'reserve',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
      {
        name: 'reservedLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
      {name: 'refTick', type: 'int24', internalType: 'int24'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revokeRole',
    inputs: [
      {name: 'role', type: 'bytes32', internalType: 'bytes32'},
      {name: 'account', type: 'address', internalType: 'address'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'settleAndTake',
    inputs: [],
    outputs: [
      {name: 'delta0', type: 'int256', internalType: 'int256'},
      {name: 'delta1', type: 'int256', internalType: 'int256'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{name: 'interfaceId', type: 'bytes4', internalType: 'bytes4'}],
    outputs: [{name: '', type: 'bool', internalType: 'bool'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tickSpacing',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'unlockCallback',
    inputs: [{name: 'rawData', type: 'bytes', internalType: 'bytes'}],
    outputs: [{name: '', type: 'bytes', internalType: 'bytes'}],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'whitelistBorrower',
    inputs: [
      {name: 'borrower', type: 'address', internalType: 'address'},
      {name: 'status', type: 'bool', internalType: 'bool'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawTokens',
    inputs: [
      {
        name: 'tokens',
        type: 'address[]',
        internalType: 'contract IERC20[]',
      },
      {name: 'amounts', type: 'uint256[]', internalType: 'uint256[]'},
      {name: 'recipient', type: 'address', internalType: 'address'},
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Borrow',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'tickLower',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'tickUpper',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'liquidity',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BorrowerWhitelisted',
    inputs: [
      {
        name: 'borrower',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'status',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Burn',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'tickLower',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'tickUpper',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'liquidity',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Mint',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'tickLower',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'tickUpper',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'liquidity',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Repay',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'tickLower',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'tickUpper',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'liquidity',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Reserve',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'tickLower',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'tickUpper',
        type: 'int24',
        indexed: false,
        internalType: 'int24',
      },
      {
        name: 'liquidity',
        type: 'uint128',
        indexed: false,
        internalType: 'uint128',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RoleAdminChanged',
    inputs: [
      {
        name: 'role',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'previousAdminRole',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'newAdminRole',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RoleGranted',
    inputs: [
      {
        name: 'role',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'account',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'sender',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RoleRevoked',
    inputs: [
      {
        name: 'role',
        type: 'bytes32',
        indexed: true,
        internalType: 'bytes32',
      },
      {
        name: 'account',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'sender',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TokenWithdrawn',
    inputs: [
      {
        name: 'token',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {type: 'error', name: 'AccessControlBadConfirmation', inputs: []},
  {
    type: 'error',
    name: 'AccessControlUnauthorizedAccount',
    inputs: [
      {name: 'account', type: 'address', internalType: 'address'},
      {name: 'neededRole', type: 'bytes32', internalType: 'bytes32'},
    ],
  },
  {
    type: 'error',
    name: 'AddressEmptyCode',
    inputs: [{name: 'target', type: 'address', internalType: 'address'}],
  },
  {type: 'error', name: 'ArrayLengthMismatch', inputs: []},
  {
    type: 'error',
    name: 'BorrowerNotWhitelisted',
    inputs: [{name: 'borrower', type: 'address', internalType: 'address'}],
  },
  {
    type: 'error',
    name: 'DeadlinePassed',
    inputs: [{name: 'deadline', type: 'uint256', internalType: 'uint256'}],
  },
  {type: 'error', name: 'FailedCall', inputs: []},
  {
    type: 'error',
    name: 'InsufficientLiquidity',
    inputs: [
      {name: 'blockTickLower', type: 'int24', internalType: 'int24'},
      {name: 'required', type: 'uint128', internalType: 'uint128'},
    ],
  },
  {
    type: 'error',
    name: 'InvalidActionType',
    inputs: [{name: 'actionType', type: 'uint8', internalType: 'uint8'}],
  },
  {type: 'error', name: 'InvalidPoolKey', inputs: []},
  {
    type: 'error',
    name: 'InvalidRefTick',
    inputs: [{name: 'tickLower', type: 'int24', internalType: 'int24'}],
  },
  {
    type: 'error',
    name: 'InvalidTickRange',
    inputs: [
      {name: 'tickLower', type: 'int24', internalType: 'int24'},
      {name: 'tickUpper', type: 'int24', internalType: 'int24'},
    ],
  },
  {
    type: 'error',
    name: 'MintTooLarge',
    inputs: [
      {
        name: 'existingLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
      {
        name: 'addedLiquidity',
        type: 'uint128',
        internalType: 'uint128',
      },
    ],
  },
  {type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: []},
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{name: 'token', type: 'address', internalType: 'address'}],
  },
  {
    type: 'error',
    name: 'SlippageExceeded',
    inputs: [
      {name: 'actual', type: 'int256', internalType: 'int256'},
      {name: 'limit', type: 'int256', internalType: 'int256'},
    ],
  },
  {type: 'error', name: 'UnauthorizedCaller', inputs: []},
  {type: 'error', name: 'ZeroAddress', inputs: []},
] as const;
